if File::exists?('Podfile.lock')
  `rm -f Podfile.lock`
end
if Gem::Version.new(`pod --version`) >= Gem::Version.new('1.9.3')
  install! 'cocoapods',
    :generate_multiple_pod_projects => true,
    :incremental_installation => true
end

platform :ios, '9.0'
#plugin 'slather'
#use_modular_headers!
#use_frameworks!

target 'Peregrine_Example' do
  pod 'Peregrine', :path => '../'
  pod 'SubPodLib', :path => '../SubPodLib'
  pod 'SwifterSwift'
  pod 'SnapKit'

  target 'Peregrine_Example_Tests' do
    inherit! :search_paths

    pod 'Specta', '~> 1.0'
    pod 'Expecta', '~> 1.0'
    
#    pod 'Quick'
#    pod 'Nimble'
  end

  post_install do |installer|
    require_relative '../Sources/Configuration.rb'
#    callback = proc { |name| name.index("Peregrine") == 0 }
    PGGenerator::configure_project(installer, {'expr' => true, 'name' => 'PGRouteDefine', 'path' => '${SRCROOT}/Peregrine_Example'})
  end
end
