coverage_service: coveralls
workspace: Example/Peregrine.xcworkspace
xcodeproj: Example/Peregrine.xcodeproj
scheme: Peregrine_Example
source_directory: Peregrine/Classes
output_directory: ./DerivedData
ignore:
  - Example/*
