coverage_service: coveralls
workspace: Example/Peregrine_Example.xcworkspace
xcodeproj: Example/Peregrine_Example.xcodeproj
scheme: Peregrine_Example
source_directory: ./Sources
ignore:
  - Example/*
  - SubPodLib/*
