/usr/local/bin/clang \
-x \
objective-c \
-target \
x86_64-apple-ios9.3-simulator \
-fmessage-length=0 \
-fdiagnostics-show-note-include-stack \
-fmacro-backtrace-limit=0 \
-std=gnu99 \
-fobjc-arc \
-fmodules \
-gmodules \
-fmodules-cache-path=/Users/rakeyang/Library/Developer/Xcode/DerivedData/ModuleCache.noindex \
-fmodules-prune-interval=86400 \
-fmodules-prune-after=345600 \
-fbuild-session-file=/Users/rakeyang/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation \
-fmodules-validate-once-per-build-session \
-Wnon-modular-include-in-framework-module \
-Werror=non-modular-include-in-framework-module \
-Wno-trigraphs \
-fpascal-strings \
-O0 \
-Wno-missing-field-initializers \
-Wno-missing-prototypes \
-Werror=return-type \
-Wno-implicit-atomic-properties \
-Werror=deprecated-objc-isa-usage \
-Wno-objc-interface-ivars \
-Werror=objc-root-class \
-Wno-arc-repeated-use-of-weak \
-Wduplicate-method-match \
-Wno-missing-braces \
-Wparentheses \
-Wswitch \
-Wunused-function \
-Wno-unused-label \
-Wno-unused-parameter \
-Wunused-variable \
-Wunused-value \
-Wempty-body \
-Wuninitialized \
-Wconditional-uninitialized \
-Wno-unknown-pragmas \
-Wno-shadow \
-Wno-four-char-constants \
-Wno-conversion \
-Wconstant-conversion \
-Wint-conversion \
-Wbool-conversion \
-Wenum-conversion \
-Wno-float-conversion \
-Wno-non-literal-null-conversion \
-Wno-objc-literal-conversion \
-Wshorten-64-to-32 \
-Wpointer-sign \
-Wno-newline-eof \
-Wno-selector \
-Wno-strict-selector-match \
-Wundeclared-selector \
-Wno-deprecated-implementations \
-DDEBUG=1 \
-DCOCOAPODS=1 \
-DOBJC_OLD_DISPATCH_PROTOTYPES=1 \
-isysroot \
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk \
-fasm-blocks \
-fstrict-aliasing \
-Wprotocol \
-Wdeprecated-declarations \
-g \
-Wno-sign-conversion \
-Wno-infinite-recursion \
-Wno-comma \
-Wno-block-capture-autoreleasing \
-Wno-strict-prototypes \
-Wno-semicolon-before-method-body \
-fobjc-abi-version=2 \
-fobjc-legacy-dispatch \
-fprofile-instr-generate \
-fcoverage-mapping \
-iquote \
/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/Peregrine_Example-generated-files.hmap \
-I/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/Peregrine_Example-own-target-headers.hmap \
-I/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/Peregrine_Example-all-non-framework-target-headers.hmap \
-ivfsoverlay \
/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/all-product-headers.yaml \
-iquote \
/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/Peregrine_Example-project-headers.hmap \
-I/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Products/Debug-iphonesimulator/include \
-I/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Products/Debug-iphonesimulator/Peregrine/Peregrine.framework/Headers \
-I/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/DerivedSources-normal/x86_64 \
-I/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/DerivedSources/x86_64 \
-I/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/DerivedSources \
-F/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Products/Debug-iphonesimulator \
-F/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Products/Debug-iphonesimulator/Peregrine \
-include \
/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/PrecompiledHeaders/PrefixHeader-ggvqzutuczjljhcrthfskvuzmcns/PrefixHeader.pch \
-MMD \
-MT \
dependencies \
-MF \
/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/Objects-normal/x86_64/PeregrineActionTest3.d \
--serialize-diagnostics \
/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/Objects-normal/x86_64/PeregrineActionTest3.dia \
-fsyntax-only \
-Xclang -ast-dump \
-c \
/Users/rakeyang/Github/Peregrine/Example/Peregrine/PeregrineActionTest3.m \