/usr/local/bin/clang-peregrine \
"/Users/rakeyang/Github/Peregrine/Example/Peregrine/PeregrineActionTest3.m" \
"/Users/rakeyang/Github/Peregrine/Example/Peregrine/PeregrineActionTest2.m" \
"/Users/rakeyang/Github/Peregrine/Example/Peregrine/FPAppDelegate.m" \
"/Users/rakeyang/Github/Peregrine/Example/Peregrine/PeregrineActionTest1.m" \
"/Users/rakeyang/Github/Peregrine/Example/Peregrine/FPViewController.m" \
"/Users/rakeyang/Github/Peregrine/Example/Peregrine/FPModel.m" \
"/Users/rakeyang/Github/Peregrine/Example/Peregrine/FPWebViewViewController.m" \
"/Users/rakeyang/Github/Peregrine/Example/Peregrine/main.m" \
"/Users/rakeyang/Github/Peregrine/Example/Peregrine/FPInsertEvent.m" \
-p="/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Products/Debug-iphonesimulator/Peregrine_Example.app/Peregrine.bundle" \
-- -ferror-limit=0 -w -fsyntax-only \
-fmessage-length=0 \
-fdiagnostics-show-note-include-stack \
-fmacro-backtrace-limit=0 \
-std=gnu99 \
-fobjc-arc \
-fmodules \
-Wno-trigraphs \
-fpascal-strings \
-O0 \
-Wno-missing-field-initializers \
-Wno-missing-prototypes \
-Werror=return-type \
-Wno-implicit-atomic-properties \
-Werror=deprecated-objc-isa-usage \
-Wno-objc-interface-ivars \
-Werror=objc-root-class \
-Wno-arc-repeated-use-of-weak \
-Wduplicate-method-match \
-Wno-missing-braces \
-Wparentheses \
-Wswitch \
-Wunused-function \
-Wno-unused-label \
-Wno-unused-parameter \
-Wunused-variable \
-Wunused-value \
-Wempty-body \
-Wuninitialized \
-Wconditional-uninitialized \
-Wno-unknown-pragmas \
-Wno-shadow \
-Wno-four-char-constants \
-Wno-conversion \
-Wconstant-conversion \
-Wint-conversion \
-Wbool-conversion \
-Wenum-conversion \
-Wno-float-conversion \
-Wno-non-literal-null-conversion \
-Wno-objc-literal-conversion \
-Wshorten-64-to-32 \
-Wpointer-sign \
-Wno-newline-eof \
-Wno-selector \
-Wno-strict-selector-match \
-Wundeclared-selector \
-Wno-deprecated-implementations \
-DDEBUG=1 \
-DCOCOAPODS=1 \
-isysroot \
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk \
-fasm-blocks \
-fstrict-aliasing \
-Wprotocol \
-Wdeprecated-declarations \
-g \
-Wno-sign-conversion \
-Wno-infinite-recursion \
-Wno-comma \
-Wno-block-capture-autoreleasing \
-Wno-strict-prototypes \
-Wno-semicolon-before-method-body \
-fobjc-abi-version=2 \
-fobjc-legacy-dispatch \
-fprofile-instr-generate \
-fcoverage-mapping \
-iquote \
/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/Peregrine_Example-generated-files.hmap \
-I/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/Peregrine_Example-own-target-headers.hmap \
-I/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/Peregrine_Example-all-non-framework-target-headers.hmap \
-iquote \
/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/Peregrine_Example-project-headers.hmap \
-I/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Products/Debug-iphonesimulator/include \
-I"/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Products/Debug-iphonesimulator/Peregrine/Peregrine.framework/Headers" \
-I/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/DerivedSources-normal/x86_64 \
-I/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/DerivedSources/x86_64 \
-I/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/Peregrine.build/Debug-iphonesimulator/Peregrine_Example.build/DerivedSources \
-F/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Products/Debug-iphonesimulator \
-F"/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Products/Debug-iphonesimulator/Peregrine" \
-MD \
-MT \
dependencies \
-MF \
/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/PrecompiledHeaders/PrefixHeader/PrefixHeader.pch.d \
-include \
/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/PrecompiledHeaders/PrefixHeader/PrefixHeader.pch.pch \
--serialize-diagnostics \
/Users/rakeyang/Library/Developer/Xcode/DerivedData/Peregrine-evincmnsbkzypdglpfjmueljrdyj/Build/Intermediates.noindex/PrecompiledHeaders/PrefixHeader/PrefixHeader.pch.dia \